from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path
from ..schemas import KnowledgeGraph, NodeType, EdgeType

_NODE_COLORS: dict[str, str] = {
    NodeType.NORMA.value: "#0f2340",
    NodeType.ARTIGO.value: "#2a5080",
    NodeType.INCISO.value: "#4a7aa0",
    NodeType.PARAGRAFO.value: "#6a9ab8",
    NodeType.ALINEA.value: "#8ab4cc",
    NodeType.ITEM.value: "#a8c8da",
    NodeType.SUBITEM.value: "#c2d8e6",
    NodeType.DEFINICAO.value: "#1a6b3a",
    NodeType.SANCAO.value: "#8b1a1a",
    NodeType.INSTITUTO.value: "#5a3a8b",
    NodeType.PAPEL.value: "#b8670a",
    NodeType.PRAZO.value: "#8b6a1a",
    NodeType.TESE.value: "#4a6b3a",
    NodeType.JURISPRUDENCIA.value: "#3a4a8b",
    NodeType.ENTIDADE.value: "#6b1a6b",
    NodeType.VERSAO.value: "#7a7a7a",
    NodeType.CONSULTA_PUBLICA.value: "#3a7a7a",
    NodeType.EXPOSICAO_MOTIVOS.value: "#4a6a3a",
}

_EDGE_COLORS: dict[str, str] = {
    EdgeType.REVOGA_EXPRESSAMENTE.value: "#c0392b",
    EdgeType.REVOGA_PARCIALMENTE.value: "#e74c3c",
    EdgeType.SUSPENDE.value: "#e67e22",
    EdgeType.ALTERA.value: "#f39c12",
    EdgeType.SUCEDE.value: "#f1c40f",
    EdgeType.REGULAMENTA.value: "#2980b9",
    EdgeType.SUBORDINA_SE_A.value: "#3498db",
    EdgeType.REMETE_A.value: "#7f8c8d",
    EdgeType.REMETE_A_EXTERNO.value: "#95a5a6",
    EdgeType.OBRIGA.value: "#8e44ad",
    EdgeType.PERMITE.value: "#27ae60",
    EdgeType.PROIBE.value: "#c0392b",
    EdgeType.DEFINE.value: "#1abc9c",
    EdgeType.TENSIONA.value: "#e74c3c",
    EdgeType.CONDICIONA.value: "#9b59b6",
    EdgeType.COMPLEMENTA.value: "#2ecc71",
    EdgeType.IMPLEMENTA.value: "#16a085",
    EdgeType.APLICA_A.value: "#8e44ad",
    EdgeType.ATRIBUI_RESPONSABILIDADE.value: "#d35400",
    EdgeType.EXCEPCIONA.value: "#e67e22",
    EdgeType.CITA.value: "#bdc3c7",
    EdgeType.CONSOLIDA.value: "#2980b9",
    EdgeType.ORIGINOU_SE_DE.value: "#7f8c8d",
    EdgeType.TRANSITORIAMENTE_APLICAVEL.value: "#95a5a6",
}


def to_json(graph: KnowledgeGraph, path: Path) -> None:
    path.write_text(
        json.dumps(graph.model_dump(mode="json"), ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )


def to_d3_json(graph: KnowledgeGraph) -> dict:
    nodes = []
    for n in graph.nodes:
        status = n.vigenciaMeta.status.value if n.vigenciaMeta else "vigente"
        layer_level = 0
        if n.normativeLayer:
            from ..schemas import LAYER_LEVELS
            layer_level = LAYER_LEVELS.get(n.normativeLayer, 0)
        nodes.append({
            "id": n.id,
            "label": n.name[:60],
            "type": n.type.value,
            "status": status,
            "layer": layer_level,
            "color": _NODE_COLORS.get(n.type.value, "#888888"),
            "summary": n.summary[:150],
            "tags": n.tags,
            "review": n.review_required,
        })

    links = []
    for e in graph.edges:
        if e.deprecated:
            continue
        links.append({
            "id": e.id,
            "source": e.source,
            "target": e.target,
            "type": e.type.value,
            "weight": e.weight,
            "implicit": e.implicit,
            "color": _EDGE_COLORS.get(e.type.value, "#999999"),
            "review": e.review_required,
            "stale": e.stale,
        })

    return {"nodes": nodes, "links": links}


def write_js_data(graph: KnowledgeGraph, output_dir: Path) -> None:
    d3_data = to_d3_json(graph)
    js_content = (
        f"// Auto-generated by Amanuense graph-builder — {datetime.now().isoformat()}\n"
        f"window.GRAPH_DATA = {json.dumps(d3_data, ensure_ascii=False, indent=2)};\n"
    )
    (output_dir / "graph-data.js").write_text(js_content, encoding="utf-8")


def build_corpus_texts(
    intermediate_dir: Path,
    graph: KnowledgeGraph,
    versoes_db: dict[str, dict] | None = None,
) -> dict:
    """Textos por nó. Com a base estruturada, as versões reais
    (dispositivo_versao, com vigência [inicio,fim)) substituem a heurística.
    """
    corpus_texts_path = intermediate_dir / "corpus_texts_builder.json"

    texts: dict = {}
    if corpus_texts_path.exists():
        raw = json.loads(corpus_texts_path.read_text(encoding="utf-8"))
        texts = raw.get("texts", {})

    for node_id, versoes in (versoes_db or {}).items():
        if node_id in texts:
            texts[node_id]["versoes"] = versoes
        else:
            ultima = versoes[max(versoes, key=lambda v: int(v[1:]))]
            texts[node_id] = {
                "textoCompleto": ultima.get("textoCompleto", ""),
                "versoes": versoes,
            }

    return {"generatedAt": datetime.now().isoformat(), "texts": texts}
